In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [2]:
## your code
result = (np.ones((1, 20)) * 2) ** np.arange(1, 21) / np.arange(1, 21)
result

array([[2.00000000e+00, 2.00000000e+00, 2.66666667e+00, 4.00000000e+00,
        6.40000000e+00, 1.06666667e+01, 1.82857143e+01, 3.20000000e+01,
        5.68888889e+01, 1.02400000e+02, 1.86181818e+02, 3.41333333e+02,
        6.30153846e+02, 1.17028571e+03, 2.18453333e+03, 4.09600000e+03,
        7.71011765e+03, 1.45635556e+04, 2.75941053e+04, 5.24288000e+04]])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [3]:
## your code
result = np.sum((np.ones(6) * 0.1) ** (3 * np.arange(6)) * (np.ones(6) * 0.2) ** (4 * np.arange(6)))
result

1.00000160000256

**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [4]:
## your code
result = np.zeros((8, 8))
result[::2, ::2] = 1
result[1::2, 1::2] = 1
result

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [5]:
result = np.random.random((5, 2))

## your code
#r = sqrt(x^2 + y^2), ang = arctg(y/x) (+pi/2pi)
r = np.sqrt(result[:, 0] ** 2 + result[:, 1] ** 2)
angle = np.arctan2(result[:, 1], result[:, 0])
result = [r, angle]
result = np.array(result).T
result

array([[0.50110143, 0.50864285],
       [0.84196491, 0.42702637],
       [0.83936235, 0.91400879],
       [0.56292745, 0.74523636],
       [0.73652913, 1.17151502]])

**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [6]:
X = np.random.random((10, 10))

## your code
result = np.unravel_index(np.argmax(X, axis = None), X.shape)
result

(0, 0)

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [7]:
X = np.random.random((10, 2))
y = np.random.random((1, 2))

## your code
# sqrt((x2-x1)^2 + (y2-y1)^2)
distance = np.sqrt((X[:, 0] - y[:, 0]) ** 2 + (X[:, 1] - y[:, 1]) ** 2)
result = X[np.argmin(distance), :]
result

array([0.52528482, 0.00585778])

**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [8]:
## your code
x_1 = np.linspace(-3, 0, 15)
x_2 = np.linspace(0, 2, 15)
x_3 = np.linspace(2, 3, 15)
y_1 = np.power(x_1, 2) + 2 * x_1 + 6
y_2 = x_2 + 6
y_3 = np.power(x_3, 2) + 4 * x_3 - 4
x = np.vstack((x_1, x_2, x_3))
y = np.vstack((y_1, y_2, y_3))

In [9]:
x

array([[-3.        , -2.78571429, -2.57142857, -2.35714286, -2.14285714,
        -1.92857143, -1.71428571, -1.5       , -1.28571429, -1.07142857,
        -0.85714286, -0.64285714, -0.42857143, -0.21428571,  0.        ],
       [ 0.        ,  0.14285714,  0.28571429,  0.42857143,  0.57142857,
         0.71428571,  0.85714286,  1.        ,  1.14285714,  1.28571429,
         1.42857143,  1.57142857,  1.71428571,  1.85714286,  2.        ],
       [ 2.        ,  2.07142857,  2.14285714,  2.21428571,  2.28571429,
         2.35714286,  2.42857143,  2.5       ,  2.57142857,  2.64285714,
         2.71428571,  2.78571429,  2.85714286,  2.92857143,  3.        ]])

In [10]:
y

array([[ 9.        ,  8.18877551,  7.46938776,  6.84183673,  6.30612245,
         5.8622449 ,  5.51020408,  5.25      ,  5.08163265,  5.00510204,
         5.02040816,  5.12755102,  5.32653061,  5.61734694,  6.        ],
       [ 6.        ,  6.14285714,  6.28571429,  6.42857143,  6.57142857,
         6.71428571,  6.85714286,  7.        ,  7.14285714,  7.28571429,
         7.42857143,  7.57142857,  7.71428571,  7.85714286,  8.        ],
       [ 8.        ,  8.57653061,  9.16326531,  9.76020408, 10.36734694,
        10.98469388, 11.6122449 , 12.25      , 12.89795918, 13.55612245,
        14.2244898 , 14.90306122, 15.59183673, 16.29081633, 17.        ]])

**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [11]:
X = np.random.random((10, 10))

## your code
X = (X.T - np.mean(X, axis = 1).T).T
np.mean(X, axis=1)

array([-1.11022302e-17, -1.11022302e-17,  1.11022302e-17,  1.11022302e-17,
        0.00000000e+00, -5.55111512e-17, -5.55111512e-17,  6.66133815e-17,
        6.66133815e-17, -1.11022302e-17])

**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [12]:
X = np.random.normal(loc=5, scale=2., size=1000)
mean_ = X.mean()
var_ = X.var()
print("выборочное среднее", mean_)
print("выборочная дисперсия", var_)

выборочное среднее 5.058378545787229
выборочная дисперсия 3.7473015678193833


In [13]:
mean = X.sum() / X.size
variance = ((X - mean) ** 2).sum() / X.size
mean, variance

(5.058378545787229, 3.7473015678193833)

**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [14]:
## your code
X = np.ones((5, 5)) 
X *= np.arange(5)
X

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [15]:
X += X.T
X

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 5.],
       [2., 3., 4., 5., 6.],
       [3., 4., 5., 6., 7.],
       [4., 5., 6., 7., 8.]])

In [16]:
X %= 5
X

array([[0., 1., 2., 3., 4.],
       [1., 2., 3., 4., 0.],
       [2., 3., 4., 0., 1.],
       [3., 4., 0., 1., 2.],
       [4., 0., 1., 2., 3.]])

**11.** Есть следующий алгоритм семплинирования, на вход функции подается вектор из целых положительных чисел и число семплов.

In [17]:
def sample(x, c):
    assert len(x) > 0
    
    s = np.sum(x)
    res = []
    for _ in range(c):
        val = s * np.random.random()
        cur, idx = 0, 0        
        while cur + x[idx] <= val:
            cur += x[idx]
            idx += 1
            
        res.append(idx)
    return res

            
sample([50, 3, 1, 7, 20], 5)    

[4, 0, 0, 0, 0]

Реализуйте данный алгоритм более оптимальным способом, без использования циклов.

In [18]:
## your code
def sample_2(x, c):
    x = np.array(x).astype("float")
    n = np.array(x).shape[0]
    s = np.sum(x)
    val = s * np.random.random(c)
    a = np.repeat(np.cumsum(x), c)
    a = a.reshape((n, c))
    a -= val
    a[a >= 0] = 100
    res = np.argmax(a, axis = 0)
    return res
print(sample([50, 3, 1, 7, 20], 5))

[0, 4, 4, 1, 4]
